# Generated by Django 2.2.1 on 2019-06-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_photos_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Catogiries',
        ),
    ]
