# Generated by Django 2.2.1 on 2019-06-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190607_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='catogiries',
            name='name',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catogiries',
            name='catogiry',
            field=models.CharField(max_length=50),
        ),
    ]
